export const AppConstants = {
  baseUrl: "https://ad.casaarch.in/api/",
  endPoints: {
    get_in_touch: "get-in-touch/",
    professional_signup: "professional-signup",
    professional_signup_patch: "professional-signup-patch",
    professional_Login: "user-login",
    user_Type: "user-type",
    professional_area_check: "professional-area-check",
    professional_service_check: "professional-service-check",
    professional_subscription_check: "professional-subscription-check",
    professional_work_profile: "professional-work-profile/",
    customer_project_choices: "customer-project-choices/",
    customer_details_leads: "customer-details-all",
    customer_details_lead: "customer-details-all",
    design_leads_all: "design-leads-all/",
    search_leads_all: "search-leads-all/",
    search_lead_add_or_remove: "search-leads-arf/",
    search_lead_fvt: "search-leads-cfl/",
    project_leads_all: "project-leads-all",
    design_lead_add_or_remove: "design-leads-arf/",
    ongoingProject_lead_add_or_remove: "project-leads-arf/",
    professional_payment: "professional-subscriber/",
    professional_profile: "professional-work-profile-token",
    professional_images: "professional-profile-images/",
  },
};
